pub mod ai;
pub mod builtins;
pub mod core;
pub mod executor;
pub mod history;
pub mod kaido_shell;
pub mod learning;
pub mod parser;
pub mod plugin;
pub mod prompt;
pub mod pty;
pub mod repl;
pub mod signals;
pub mod skills;
pub mod theme;

pub use builtins::{parse_builtin, Builtin, BuiltinResult, ShellEnvironment};
pub use core::Shell;
pub use executor::CommandExecutor;
pub use history::{default_history_path, ensure_history_dir, HistoryConfig};
pub use kaido_shell::{KaidoShell, ShellConfig};
pub use learning::{LearningTracker, SkillCategory};
pub use parser::{CommandParser, ParseError, ParsedCommand};
pub use prompt::PromptBuilder;
pub use pty::{PtyExecutionResult, PtyExecutor};
pub use repl::run_agent_repl;
pub use signals::{SignalHandler, TerminalSize};
pub use theme::Theme;
